### ISSUE TITLE
hard to get going nowadays

### ISSUE THREAD

**Issue by ec1oud** [fjballest/octopus#1]
http://lsub.org/export/o.zip is missing.  I found it on archive.org.

cpu% unzip /usr/rutledge/download/octopus/o.zip
unzip: can't seek to contents of <stdin>
trying to re-run assuming -s

So I had to unzip on Linux and create a tarball instead; that I can untar on Plan9.

I have 9front on a raspberry pi; thought I'd try to install on that, but there are no arm binaries.

I have 9front 64-bit on a laptop; thought I'd try to install on that, but there are only 386 binaries, and apparently plan9 can't run 32-bit binaries on a 64-bit OS.

cpu% Plan9/386/bin/emu
Plan9/386/bin/emu: exec header invalid

I guess next I can try on an old PIII laptop with the 32-bit 9front, but that one doesn't have working ethernet because of missing drivers for one of the most popular pcmcia ethernet cards.  Maybe can try another old thinkpad with the 32-bit version.

Anyway I guess I should figure out how to compile for the missing architectures, but I don't have much experience with inferno yet, and only a little on plan9 so far.

**Comment by ec1oud** [comment]
I got it going on an X60s on Plan9 32-bit, and also on 64-bit Linux (but only locally, not across the network from one to the other).  Seems I have to run inferno twice in two windows (cd ~/octopus; Linux/386/bin/emu -r $PWD), then run o/pcrc in one and o/termrc in the other, then I get a third window with o/mero ui.  And in that third window, there is an inferno prompt with a flashing cursor, overlaying the top of o/mero.  Each time I try to type a command in an o/mero window, every other keystroke goes to the inferno prompt instead.  So mousing around to open and close files works, but many other things seem impractical so far.  Also, the window is rather small and not resizable.

![octopus-omero-ui](https://user-images.githubusercontent.com/2946740/139555585-6a68b3e7-0972-4de7-997d-6d5ab5a3a0be.png)

**Comment by ec1oud** [comment]
Anyway I'm trying it because I had a similar idea to represent a UI hierarchy with a virtual filesystem and wanted to see what I can learn from this one.

**Comment by fjballest** [comment]
try out with the clive ui ideas. I think they are better. hth. 
Octopus is here for reference. Too old to run, probably.
